### ISSUE TITLE
Update Makefile

### ISSUE THREAD

**Issue by horizon2038** [horizon2038/A9N#1]
## Summary
The current Makefile is messy and dirty, so it needs to be cleaned up.
## Tasks
- [ ] Fix automatic resolve dependencies.
- [ ] Unify the syntax of Makefiles.
- [ ] Create clear comments.
