### ISSUE TITLE
Migration to CMake

### ISSUE THREAD

**Issue by horizon2038** [horizon2038/A9N#10]
## Summary
Stop using the old `Make` and migrate to a `CMake` based build system.

## Tasks
- [x] Create `CMakeLists.txt` for each `src/kernel`, `src/hal`, `src/liba9n`
- [x] Call recursively based on `{ARCH}` variables
- [ ] Remove old `Makefile`
- [x] Bug fixes for proper startup
