### ISSUE TITLE
Make Capabilities

### ISSUE THREAD

**Issue by horizon2038** [horizon2038/A9N#2]
## Summary
Add capabilities to the kernel to make it more secure.
## Tasks
- [ ] Implement various capability structures.
- [ ] Implement capability space exploration.
- [ ] Remove the physical memory management policy from the kernel.
